version: "3"
services:
  postgresdb:
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=cropto_db

  web:
    build: webapp/
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - postgresdb
    volumes:
      - ./webapp/opt/webapp

  etl:
    build: etl/
    volumes:
    - ./etl/:/app
    depends_on:
    - postgresdb

  tweet_collector:
    build: market_collector/
    volumes:
    - ./market_collector/:/app
    depends_on:
    - mongodb